huuhCREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar(20) NOT NULL,
  "lastname" varchar(20) NOT NULL,
  "email" varchar(20) NOT NULL,
  "dob" date NOT NULL,
  "role_id" integer NOT NULL
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "description" text NOT NULL,
  "teacher_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  "level_id" int NOT NULL
);

CREATE TABLE "courses_videos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video" varchar(50) NOT NULL,
  "url" varchar(30) NOT NULL,
  "course_id" integer NOT NULL
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar(30) NOT NULL
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(30) NOT NULL
);

CREATE TABLE "levels" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(30) NOT NULL
);

CREATE TABLE "courses_users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "course_id" integer NOT NULL
);

ALTER TABLE "courses_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses_users" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");



ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

/* PARA AGREGARLE DATOS A LAS TABLAS  */
INSERT INTO roles (role) VALUES ('Administrador del sitio') , ('Gestor de contenido');
SELECT * FROM roles;
INSERT INTO levels (level) VALUES ('Intermedio') , ('Inicial');
SELECT * FROM levels;
INSERT INTO categories (category) VALUES ('alumno oral') , ('alumno visual');
SELECT * FROM categories;
 
 /*  AGREGARLE INFORMACION A LAS TABLAS CON LLAVES FORANEAS*/
 INSERT INTO users (firstname, lastname, email, dob, role_id) VALUES
('Dorian',1) , ('Sanchez',1) , ('dorian11sanchez@gmail.com',1), ('5-01-2001',1);

 INSERT INTO users (firstname, lastname, email, dob, role_id) VALUES
('Dorian',2) , ('Sanchez',2) , ('dorian11sanchez@gmail.com',2), ('5-01-2001',2);

INSERT INTO courses (title, description, teacher_id, category_id, level_id) VALUES
('matematicas',1,1,1) , ('algebra',1,1,1)

INSERT INTO courses (title, description, teacher_id, category_id, level_id) VALUES
('lenguaje',1,1,1) , ('vocales y consonantes',1,1,1)


/* Tabla foranea */
INSERT INTO  courses_users (user_id , course_id) VALUES (1,1) , (2,2);


INSERT INTO  courses_users (video , url, course_id) VALUES ('algebra',1) , ('https://guao.org/sites/default/files/biblioteca/%C3%81lgebra%20de%20Baldor.pdf',1);

INSERT INTO  courses_users (video , url, course_id) VALUES ('lenguaje',1) , ('https://es.wikipedia.org/wiki/Lenguaje',2);